services:
  - type: web
    name: fishbanks-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://fishbanks-game.vercel.app
